-- Create admin user with default credentials
-- Password: HikigaiAdmin2024! (should be changed after first login)

-- First, hash the password using bcrypt (this will be done by the application)
-- The actual password hash will be generated by the Node.js bcrypt library

-- Insert admin user with hashed password
INSERT INTO admin_users (id, email, password_hash, is_active, created_at, updated_at)
VALUES (
  gen_random_uuid(),
  'krish@hikigai.ai',
  '$2a$12$UoNyJsDuVKmskWG1y9LGS.1C7EPRMVqKmWS/WBq5iZnmmbwSZavCO', -- This is bcrypt hash of 'HikigaiAdmin2024!'
  true,
  now(),
  now()
)
ON CONFLICT (email) DO NOTHING;

-- Note: The actual password is 'HikigaiAdmin2024!' 
-- This should be changed immediately after first login
